---
- name: Deploy common tenant jobs
  hosts: localhost
  gather_facts: false
  vars:
    controller_templates:
      - name: Data Refresh
        job_type: run
        project: Multi-Tenant
        playbook: dummy.yml
        ask_job_type_on_launch: true
        ask_credential_on_launch: true
        ask_inventory_on_launch: true
      - name: App Restart
        job_type: run
        project: Multi-Tenant
        playbook: dummy.yml
        ask_job_type_on_launch: true
        ask_credential_on_launch: true
        ask_inventory_on_launch: true
      - name: Enable Debug
        job_type: run
        project: Multi-Tenant
        playbook: dummy.yml
        ask_job_type_on_launch: true
        ask_credential_on_launch: true
        ask_inventory_on_launch: true

  roles:
    - infra.aap_configuration.controller_job_templates
