---
- ansible.builtin.import_playbook: deploy_jobs.yml
- ansible.builtin.import_playbook: deploy_tenant.yml
  vars:
    tenant_name: tenant1

- name: Configure Demo Users
  hosts: localhost
  gather_facts: false
  vars_files:
    - common_vars/demo.yml
    - tenant_vars/tenant1.yml
  
  roles:
    - infra.aap_configuration.gateway_users
    - infra.aap_configuration.controller_roles
    - infra.aap_configuration.controller_credential_types
    - infra.aap_configuration.controller_credentials
    - infra.aap_configuration.controller_job_templates
