---
- name: Deploy tenant from vars
  hosts: localhost
  gather_facts: false
  vars:
    tenant_org: Multi-Tenant
    multi_org: false
  vars_files:
    - common_vars/roles.yml
    - "tenant_vars/{{tenant_name}}.yml"

  tasks:
    - name: Set Tenant Org
      set_fact:
        tenant_org: "{{ tenant_name }}"
      when: multi_org

    - name: Create Org
      ansible.platform.organization:
        name: "{{ tenant_org }}"
        state: present

    - name: Create Team
      ansible.platform.team:
        name: "{{ tenant_name }} Users"
        organization: "{{ tenant_org }}"

    - name: Create Creds
      ansible.controller.credential:
        name: "{{ tenant_name }}-{{ item }}"
        organization: "{{ tenant_org }}"
        state: exists
        credential_type: Amazon Web Services
      loop: "{{ tenant_cloud_accts }}"
      when: 
        - tenant_cloud_accts is defined
      register: tenant_creds

    - name: Create Inventory
      ansible.controller.inventory:
        name: "{{ tenant_name }}"
        organization: "{{ tenant_org }}"
        state: present
        variables: "{{ tenant_vars }}"
      register: tenant_inventory

    - name: Create Inventory Sources
      ansible.controller.inventory_source:
        name: "{{ tenant_name }}-{{ item }}"
        organization: "{{ tenant_org }}"
        inventory: "{{ tenant_name }}"
        credential: "{{ tenant_name }}-{{ item }}"
        source: ec2
        overwrite: true
        overwrite_vars: true
      loop: "{{ tenant_cloud_accts }}"
      when: 
        - tenant_cloud_accts is defined

    - name: Assign Roles
      ansible.builtin.include_role:
        name: infra.aap_configuration.controller_roles

    #- name: Assign inventory permissions
    #  ansible.controller.role_team_assignment:
    #    role_definition: Inventory Use
    #    object_id: "{{ tenant_inventory.id }}"
    #    team: "{{ tenant_name }} Users"
    #    state: present
#
    #- name: Assign credential permissions
    #  ansible.controller.role_team_assignment:
    #    role_definition: Credential Use
    #    object_id: "{{ item.id }}"
    #    team: "{{ tenant_name }} Users"
    #    state: present
    #  loop: "{{ tenant_creds.results }}"
