---
- name: Pre-checks
  hosts: localhost
  gather_facts: no
  tasks:
    - name: check for required vars
      ansible.builtin.assert:
        that:
          - playbook_name is defined
          - collection_name is defined
        fail_msg: " 'playbook_name' or 'collection_name' are not defined"

- name: "Include {{ playbook_name }} from {{ collection_name }}"
  ansible.builtin.import_playbook: "{{ collection_name }}.{{ playbook_name }}"
  vars: "{{ runner_vars }}"
